/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentListResponse,
  AgentResponse,
  InvokeAgentRequest,
  InvokeAgentResponse,
} from '../models/index';
import {
    AgentListResponseFromJSON,
    AgentListResponseToJSON,
    AgentResponseFromJSON,
    AgentResponseToJSON,
    InvokeAgentRequestFromJSON,
    InvokeAgentRequestToJSON,
    InvokeAgentResponseFromJSON,
    InvokeAgentResponseToJSON,
} from '../models/index';

export interface GetAgentRequest {
    agentId: string;
}

export interface InvokeAgentOperationRequest {
    agentId: string;
    invokeAgentRequest: InvokeAgentRequest;
}

export interface ListAgentsRequest {
    instanceId?: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Get agent details by ID.
     */
    async getAgentRaw(requestParameters: GetAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling getAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agents/{agentId}`;
        urlPath = urlPath.replace(`{${"agentId"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Get agent details by ID.
     */
    async getAgent(requestParameters: GetAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.getAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sends a `chat_message` to the specified agent via Message Service channel-primitives and blocks until the agent replies (or times out).  For streaming responses, set `Accept: text/event-stream` — the response body will be Server-Sent Events with `delta` and `done` event types. 
     * Send a message to an agent and receive a reply.
     */
    async invokeAgentRaw(requestParameters: InvokeAgentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvokeAgentResponse>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling invokeAgent().'
            );
        }

        if (requestParameters['invokeAgentRequest'] == null) {
            throw new runtime.RequiredError(
                'invokeAgentRequest',
                'Required parameter "invokeAgentRequest" was null or undefined when calling invokeAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agents/{agentId}/invoke`;
        urlPath = urlPath.replace(`{${"agentId"}}`, encodeURIComponent(String(requestParameters['agentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvokeAgentRequestToJSON(requestParameters['invokeAgentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvokeAgentResponseFromJSON(jsonValue));
    }

    /**
     * Sends a `chat_message` to the specified agent via Message Service channel-primitives and blocks until the agent replies (or times out).  For streaming responses, set `Accept: text/event-stream` — the response body will be Server-Sent Events with `delta` and `done` event types. 
     * Send a message to an agent and receive a reply.
     */
    async invokeAgent(requestParameters: InvokeAgentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvokeAgentResponse> {
        const response = await this.invokeAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List agents owned by the caller.
     */
    async listAgentsRaw(requestParameters: ListAgentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['instanceId'] != null) {
            queryParameters['instance_id'] = requestParameters['instanceId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentListResponseFromJSON(jsonValue));
    }

    /**
     * List agents owned by the caller.
     */
    async listAgents(requestParameters: ListAgentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentListResponse> {
        const response = await this.listAgentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
