/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeployModelsListResponse,
  DeployRegionsListResponse,
  ProvidersListResponse,
} from '../models/index';
import {
    DeployModelsListResponseFromJSON,
    DeployModelsListResponseToJSON,
    DeployRegionsListResponseFromJSON,
    DeployRegionsListResponseToJSON,
    ProvidersListResponseFromJSON,
    ProvidersListResponseToJSON,
} from '../models/index';

export interface ListDeployModelsRequest {
    agentFramework?: string;
}

export interface ListDeployRegionsRequest {
    providerId?: string;
}

/**
 * 
 */
export class DeployApi extends runtime.BaseAPI {

    /**
     * List deploy models
     */
    async listDeployModelsRaw(requestParameters: ListDeployModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeployModelsListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['agentFramework'] != null) {
            queryParameters['agentFramework'] = requestParameters['agentFramework'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/deploy/models`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeployModelsListResponseFromJSON(jsonValue));
    }

    /**
     * List deploy models
     */
    async listDeployModels(requestParameters: ListDeployModelsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeployModelsListResponse> {
        const response = await this.listDeployModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List deploy regions
     */
    async listDeployRegionsRaw(requestParameters: ListDeployRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeployRegionsListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['providerId'] != null) {
            queryParameters['providerId'] = requestParameters['providerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/deploy/regions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeployRegionsListResponseFromJSON(jsonValue));
    }

    /**
     * List deploy regions
     */
    async listDeployRegions(requestParameters: ListDeployRegionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeployRegionsListResponse> {
        const response = await this.listDeployRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List available providers (catalog)
     */
    async listProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProvidersListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/providers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProvidersListResponseFromJSON(jsonValue));
    }

    /**
     * List available providers (catalog)
     */
    async listProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProvidersListResponse> {
        const response = await this.listProvidersRaw(initOverrides);
        return await response.value();
    }

}
