/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeployInstanceRequest,
  InstancePageResponse,
  InstanceResponse,
  StringResponse,
} from '../models/index';
import {
    DeployInstanceRequestFromJSON,
    DeployInstanceRequestToJSON,
    InstancePageResponseFromJSON,
    InstancePageResponseToJSON,
    InstanceResponseFromJSON,
    InstanceResponseToJSON,
    StringResponseFromJSON,
    StringResponseToJSON,
} from '../models/index';

export interface DeployInstanceOperationRequest {
    deployInstanceRequest: DeployInstanceRequest;
}

export interface DestroyInstanceRequest {
    id: string;
}

export interface GetInstanceRequest {
    id: string;
}

export interface ListInstancesRequest {
    page?: number;
    pageSize?: number;
    status?: string;
    providerId?: string;
    agentFramework?: string;
    clusterId?: string;
    search?: string;
}

export interface RestartInstanceRequest {
    id: string;
}

export interface StartInstanceRequest {
    id: string;
}

export interface StopInstanceRequest {
    id: string;
}

/**
 * 
 */
export class InstancesApi extends runtime.BaseAPI {

    /**
     * Deploy a new instance (catalog-driven via `variantId` or explicit).
     */
    async deployInstanceRaw(requestParameters: DeployInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceResponse>> {
        if (requestParameters['deployInstanceRequest'] == null) {
            throw new runtime.RequiredError(
                'deployInstanceRequest',
                'Required parameter "deployInstanceRequest" was null or undefined when calling deployInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeployInstanceRequestToJSON(requestParameters['deployInstanceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceResponseFromJSON(jsonValue));
    }

    /**
     * Deploy a new instance (catalog-driven via `variantId` or explicit).
     */
    async deployInstance(requestParameters: DeployInstanceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceResponse> {
        const response = await this.deployInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Destroy (terminate) an instance
     */
    async destroyInstanceRaw(requestParameters: DestroyInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling destroyInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Destroy (terminate) an instance
     */
    async destroyInstance(requestParameters: DestroyInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.destroyInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an instance by id
     */
    async getInstanceRaw(requestParameters: GetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceResponseFromJSON(jsonValue));
    }

    /**
     * Get an instance by id
     */
    async getInstance(requestParameters: GetInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceResponse> {
        const response = await this.getInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the caller\'s instances
     */
    async listInstancesRaw(requestParameters: ListInstancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstancePageResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['providerId'] != null) {
            queryParameters['providerId'] = requestParameters['providerId'];
        }

        if (requestParameters['agentFramework'] != null) {
            queryParameters['agentFramework'] = requestParameters['agentFramework'];
        }

        if (requestParameters['clusterId'] != null) {
            queryParameters['clusterId'] = requestParameters['clusterId'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstancePageResponseFromJSON(jsonValue));
    }

    /**
     * List the caller\'s instances
     */
    async listInstances(requestParameters: ListInstancesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstancePageResponse> {
        const response = await this.listInstancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restart an instance
     */
    async restartInstanceRaw(requestParameters: RestartInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling restartInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances/{id}/restart`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceResponseFromJSON(jsonValue));
    }

    /**
     * Restart an instance
     */
    async restartInstance(requestParameters: RestartInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceResponse> {
        const response = await this.restartInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start an instance
     */
    async startInstanceRaw(requestParameters: StartInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling startInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances/{id}/start`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceResponseFromJSON(jsonValue));
    }

    /**
     * Start an instance
     */
    async startInstance(requestParameters: StartInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceResponse> {
        const response = await this.startInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop an instance
     */
    async stopInstanceRaw(requestParameters: StopInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InstanceResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling stopInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/instances/{id}/stop`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InstanceResponseFromJSON(jsonValue));
    }

    /**
     * Stop an instance
     */
    async stopInstance(requestParameters: StopInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InstanceResponse> {
        const response = await this.stopInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
