/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present on failure. `code`/`message` are the JSON-RPC fields.
 * @export
 * @interface A2AJSONRPCResponseError
 */
export interface A2AJSONRPCResponseError {
    /**
     * 
     * @type {number}
     * @memberof A2AJSONRPCResponseError
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof A2AJSONRPCResponseError
     */
    message: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof A2AJSONRPCResponseError
     */
    data?: { [key: string]: any; };
}

/**
 * Check if a given object implements the A2AJSONRPCResponseError interface.
 */
export function instanceOfA2AJSONRPCResponseError(value: object): value is A2AJSONRPCResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function A2AJSONRPCResponseErrorFromJSON(json: any): A2AJSONRPCResponseError {
    return A2AJSONRPCResponseErrorFromJSONTyped(json, false);
}

export function A2AJSONRPCResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): A2AJSONRPCResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function A2AJSONRPCResponseErrorToJSON(json: any): A2AJSONRPCResponseError {
    return A2AJSONRPCResponseErrorToJSONTyped(json, false);
}

export function A2AJSONRPCResponseErrorToJSONTyped(value?: A2AJSONRPCResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
    };
}

