/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { A2AJSONRPCRequestId } from './A2AJSONRPCRequestId';
import {
    A2AJSONRPCRequestIdFromJSON,
    A2AJSONRPCRequestIdFromJSONTyped,
    A2AJSONRPCRequestIdToJSON,
    A2AJSONRPCRequestIdToJSONTyped,
} from './A2AJSONRPCRequestId';

/**
 * 
 * @export
 * @interface A2AJSONRPCRequest
 */
export interface A2AJSONRPCRequest {
    /**
     * 
     * @type {string}
     * @memberof A2AJSONRPCRequest
     */
    jsonrpc: A2AJSONRPCRequestJsonrpcEnum;
    /**
     * 
     * @type {A2AJSONRPCRequestId}
     * @memberof A2AJSONRPCRequest
     */
    id?: A2AJSONRPCRequestId | null;
    /**
     * Standard A2A v1.0 methods (`SendMessage`, `GetTask`, `CancelTask`,
     * `ListTasks`, `SendStreamingMessage`, `SubscribeToTask`,
     * `SetPushNotificationConfig`, `GetPushNotificationConfig`,
     * `ListPushNotificationConfigs`, `DeletePushNotificationConfig`) or
     * BeeOS extensions (`CompleteTask`, `UpdateStatus`). Legacy aliases
     * (`message/send`, `tasks/get`, `tasks/cancel`, `tasks/list`,
     * `message/stream`, `tasks/resubscribe`, `tasks/complete`,
     * `tasks/updateStatus`, `tasks/pushNotification/...`) are also
     * accepted.
     * 
     * @type {string}
     * @memberof A2AJSONRPCRequest
     */
    method: string;
    /**
     * Method-specific params object; see A2A v1.0 spec.
     * @type {{ [key: string]: any; }}
     * @memberof A2AJSONRPCRequest
     */
    params?: { [key: string]: any; };
}


/**
 * @export
 */
export const A2AJSONRPCRequestJsonrpcEnum = {
    _20: '2.0'
} as const;
export type A2AJSONRPCRequestJsonrpcEnum = typeof A2AJSONRPCRequestJsonrpcEnum[keyof typeof A2AJSONRPCRequestJsonrpcEnum];


/**
 * Check if a given object implements the A2AJSONRPCRequest interface.
 */
export function instanceOfA2AJSONRPCRequest(value: object): value is A2AJSONRPCRequest {
    if (!('jsonrpc' in value) || value['jsonrpc'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function A2AJSONRPCRequestFromJSON(json: any): A2AJSONRPCRequest {
    return A2AJSONRPCRequestFromJSONTyped(json, false);
}

export function A2AJSONRPCRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): A2AJSONRPCRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'],
        'id': json['id'] == null ? undefined : A2AJSONRPCRequestIdFromJSON(json['id']),
        'method': json['method'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function A2AJSONRPCRequestToJSON(json: any): A2AJSONRPCRequest {
    return A2AJSONRPCRequestToJSONTyped(json, false);
}

export function A2AJSONRPCRequestToJSONTyped(value?: A2AJSONRPCRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': A2AJSONRPCRequestIdToJSON(value['id']),
        'method': value['method'],
        'params': value['params'],
    };
}

