/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { A2AJSONRPCResponseError } from './A2AJSONRPCResponseError';
import {
    A2AJSONRPCResponseErrorFromJSON,
    A2AJSONRPCResponseErrorFromJSONTyped,
    A2AJSONRPCResponseErrorToJSON,
    A2AJSONRPCResponseErrorToJSONTyped,
} from './A2AJSONRPCResponseError';
import type { A2AJSONRPCResponseId } from './A2AJSONRPCResponseId';
import {
    A2AJSONRPCResponseIdFromJSON,
    A2AJSONRPCResponseIdFromJSONTyped,
    A2AJSONRPCResponseIdToJSON,
    A2AJSONRPCResponseIdToJSONTyped,
} from './A2AJSONRPCResponseId';

/**
 * 
 * @export
 * @interface A2AJSONRPCResponse
 */
export interface A2AJSONRPCResponse {
    /**
     * 
     * @type {string}
     * @memberof A2AJSONRPCResponse
     */
    jsonrpc: A2AJSONRPCResponseJsonrpcEnum;
    /**
     * 
     * @type {A2AJSONRPCResponseId}
     * @memberof A2AJSONRPCResponse
     */
    id: A2AJSONRPCResponseId | null;
    /**
     * Present on success; method-specific result shape.
     * @type {{ [key: string]: any; }}
     * @memberof A2AJSONRPCResponse
     */
    result?: { [key: string]: any; };
    /**
     * 
     * @type {A2AJSONRPCResponseError}
     * @memberof A2AJSONRPCResponse
     */
    error?: A2AJSONRPCResponseError;
}


/**
 * @export
 */
export const A2AJSONRPCResponseJsonrpcEnum = {
    _20: '2.0'
} as const;
export type A2AJSONRPCResponseJsonrpcEnum = typeof A2AJSONRPCResponseJsonrpcEnum[keyof typeof A2AJSONRPCResponseJsonrpcEnum];


/**
 * Check if a given object implements the A2AJSONRPCResponse interface.
 */
export function instanceOfA2AJSONRPCResponse(value: object): value is A2AJSONRPCResponse {
    if (!('jsonrpc' in value) || value['jsonrpc'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function A2AJSONRPCResponseFromJSON(json: any): A2AJSONRPCResponse {
    return A2AJSONRPCResponseFromJSONTyped(json, false);
}

export function A2AJSONRPCResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): A2AJSONRPCResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'],
        'id': A2AJSONRPCResponseIdFromJSON(json['id']),
        'result': json['result'] == null ? undefined : json['result'],
        'error': json['error'] == null ? undefined : A2AJSONRPCResponseErrorFromJSON(json['error']),
    };
}

export function A2AJSONRPCResponseToJSON(json: any): A2AJSONRPCResponse {
    return A2AJSONRPCResponseToJSONTyped(json, false);
}

export function A2AJSONRPCResponseToJSONTyped(value?: A2AJSONRPCResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': A2AJSONRPCResponseIdToJSON(value['id']),
        'result': value['result'],
        'error': A2AJSONRPCResponseErrorToJSON(value['error']),
    };
}

