/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentDTO } from './AgentDTO';
import {
    AgentDTOFromJSON,
    AgentDTOFromJSONTyped,
    AgentDTOToJSON,
    AgentDTOToJSONTyped,
} from './AgentDTO';

/**
 * 
 * @export
 * @interface AgentResponse
 */
export interface AgentResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AgentResponse
     */
    success: AgentResponseSuccessEnum;
    /**
     * 
     * @type {AgentDTO}
     * @memberof AgentResponse
     */
    data: AgentDTO;
}


/**
 * @export
 */
export const AgentResponseSuccessEnum = {
    True: true
} as const;
export type AgentResponseSuccessEnum = typeof AgentResponseSuccessEnum[keyof typeof AgentResponseSuccessEnum];


/**
 * Check if a given object implements the AgentResponse interface.
 */
export function instanceOfAgentResponse(value: object): value is AgentResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AgentResponseFromJSON(json: any): AgentResponse {
    return AgentResponseFromJSONTyped(json, false);
}

export function AgentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': AgentDTOFromJSON(json['data']),
    };
}

export function AgentResponseToJSON(json: any): AgentResponse {
    return AgentResponseToJSONTyped(json, false);
}

export function AgentResponseToJSONTyped(value?: AgentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': AgentDTOToJSON(value['data']),
    };
}

