/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeployRegionItem } from './DeployRegionItem';
import {
    DeployRegionItemFromJSON,
    DeployRegionItemFromJSONTyped,
    DeployRegionItemToJSON,
    DeployRegionItemToJSONTyped,
} from './DeployRegionItem';

/**
 * 
 * @export
 * @interface DeployRegionsListResponse
 */
export interface DeployRegionsListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DeployRegionsListResponse
     */
    success: DeployRegionsListResponseSuccessEnum;
    /**
     * 
     * @type {Array<DeployRegionItem>}
     * @memberof DeployRegionsListResponse
     */
    data: Array<DeployRegionItem>;
}


/**
 * @export
 */
export const DeployRegionsListResponseSuccessEnum = {
    True: true
} as const;
export type DeployRegionsListResponseSuccessEnum = typeof DeployRegionsListResponseSuccessEnum[keyof typeof DeployRegionsListResponseSuccessEnum];


/**
 * Check if a given object implements the DeployRegionsListResponse interface.
 */
export function instanceOfDeployRegionsListResponse(value: object): value is DeployRegionsListResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeployRegionsListResponseFromJSON(json: any): DeployRegionsListResponse {
    return DeployRegionsListResponseFromJSONTyped(json, false);
}

export function DeployRegionsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployRegionsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(DeployRegionItemFromJSON)),
    };
}

export function DeployRegionsListResponseToJSON(json: any): DeployRegionsListResponse {
    return DeployRegionsListResponseToJSONTyped(json, false);
}

export function DeployRegionsListResponseToJSONTyped(value?: DeployRegionsListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(DeployRegionItemToJSON)),
    };
}

