/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeployModelItem
 */
export interface DeployModelItem {
    /**
     * 
     * @type {string}
     * @memberof DeployModelItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DeployModelItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DeployModelItem
     */
    tier: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeployModelItem
     */
    reasoning: boolean;
}

/**
 * Check if a given object implements the DeployModelItem interface.
 */
export function instanceOfDeployModelItem(value: object): value is DeployModelItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('reasoning' in value) || value['reasoning'] === undefined) return false;
    return true;
}

export function DeployModelItemFromJSON(json: any): DeployModelItem {
    return DeployModelItemFromJSONTyped(json, false);
}

export function DeployModelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployModelItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'tier': json['tier'],
        'reasoning': json['reasoning'],
    };
}

export function DeployModelItemToJSON(json: any): DeployModelItem {
    return DeployModelItemToJSONTyped(json, false);
}

export function DeployModelItemToJSONTyped(value?: DeployModelItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tier': value['tier'],
        'reasoning': value['reasoning'],
    };
}

