/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Either supply a **catalog** `variantId` (authoritative — lifts
 * `agentFramework` / `providerId` / region / scheduling hints from the
 * variant) **or** provide an explicit `agentFramework` (+ optional
 * `providerId`). Client-supplied scheduling fields (ownershipPreference /
 * maxPricePerHour / resourceTypeHint) are **not** accepted here; the
 * catalog variant is the source of truth.
 * 
 * @export
 * @interface DeployInstanceRequest
 */
export interface DeployInstanceRequest {
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    variantId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    agentFramework?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    providerId?: string;
    /**
     * Free-form provider-specific configuration merged with the catalog
     * config (catalog wins on key conflicts).
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DeployInstanceRequest
     */
    providerConfig?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    modelPrimary?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeployInstanceRequest
     */
    models?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    systemPrompt?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DeployInstanceRequest
     */
    mcpServers?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    bridgeId?: string;
    /**
     * Alternate name for `providerConfig`; same semantics. Used by the
     * variant-driven path to layer user extras (apiKeys / apiBaseUrls)
     * on top of the catalog config.
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DeployInstanceRequest
     */
    config?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    clusterId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployInstanceRequest
     */
    preferredRegion?: string;
}

/**
 * Check if a given object implements the DeployInstanceRequest interface.
 */
export function instanceOfDeployInstanceRequest(value: object): value is DeployInstanceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DeployInstanceRequestFromJSON(json: any): DeployInstanceRequest {
    return DeployInstanceRequestFromJSONTyped(json, false);
}

export function DeployInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'variantId': json['variantId'] == null ? undefined : json['variantId'],
        'agentFramework': json['agentFramework'] == null ? undefined : json['agentFramework'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'providerConfig': json['providerConfig'] == null ? undefined : json['providerConfig'],
        'name': json['name'],
        'modelPrimary': json['modelPrimary'] == null ? undefined : json['modelPrimary'],
        'models': json['models'] == null ? undefined : json['models'],
        'systemPrompt': json['systemPrompt'] == null ? undefined : json['systemPrompt'],
        'mcpServers': json['mcpServers'] == null ? undefined : json['mcpServers'],
        'bridgeId': json['bridgeId'] == null ? undefined : json['bridgeId'],
        'config': json['config'] == null ? undefined : json['config'],
        'clusterId': json['clusterId'] == null ? undefined : json['clusterId'],
        'preferredRegion': json['preferredRegion'] == null ? undefined : json['preferredRegion'],
    };
}

export function DeployInstanceRequestToJSON(json: any): DeployInstanceRequest {
    return DeployInstanceRequestToJSONTyped(json, false);
}

export function DeployInstanceRequestToJSONTyped(value?: DeployInstanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'variantId': value['variantId'],
        'agentFramework': value['agentFramework'],
        'providerId': value['providerId'],
        'providerConfig': value['providerConfig'],
        'name': value['name'],
        'modelPrimary': value['modelPrimary'],
        'models': value['models'],
        'systemPrompt': value['systemPrompt'],
        'mcpServers': value['mcpServers'],
        'bridgeId': value['bridgeId'],
        'config': value['config'],
        'clusterId': value['clusterId'],
        'preferredRegion': value['preferredRegion'],
    };
}

