/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceDataDTO
 */
export interface InstanceDataDTO {
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    agentFramework: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    osType: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    hostingType: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    cloudProvider: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    modelPrimary: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceDataDTO
     */
    models: Array<string>;
    /**
     * One of `pending` | `provisioning` | `running` | `stopped` |
     * `terminated`.
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    status: string;
    /**
     * One of `running` | `stopped` | `terminated`.
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    desiredStatus: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    bridgeId: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    identityId: string;
    /**
     * 
     * @type {number}
     * @memberof InstanceDataDTO
     */
    totalRunSeconds: number;
    /**
     * One of `unknown` | `online` | `offline`.
     * @type {string}
     * @memberof InstanceDataDTO
     */
    connectivity: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    haltReason?: string;
    /**
     * Sanitized provider config (apiKeys stripped). Raw JSON object.
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InstanceDataDTO
     */
    providerConfig: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    publicIp?: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    clusterId?: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    imageRef?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InstanceDataDTO
     */
    isTrial?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    systemPrompt?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InstanceDataDTO
     */
    mcpServers?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    stoppedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    statusEnteredAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    connectivityUpdatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof InstanceDataDTO
     */
    screenshotUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof InstanceDataDTO
     */
    screenshotUpdatedAt?: Date;
}

/**
 * Check if a given object implements the InstanceDataDTO interface.
 */
export function instanceOfInstanceDataDTO(value: object): value is InstanceDataDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('agentFramework' in value) || value['agentFramework'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('osType' in value) || value['osType'] === undefined) return false;
    if (!('hostingType' in value) || value['hostingType'] === undefined) return false;
    if (!('cloudProvider' in value) || value['cloudProvider'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('modelPrimary' in value) || value['modelPrimary'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('desiredStatus' in value) || value['desiredStatus'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('bridgeId' in value) || value['bridgeId'] === undefined) return false;
    if (!('identityId' in value) || value['identityId'] === undefined) return false;
    if (!('totalRunSeconds' in value) || value['totalRunSeconds'] === undefined) return false;
    if (!('connectivity' in value) || value['connectivity'] === undefined) return false;
    if (!('providerConfig' in value) || value['providerConfig'] === undefined) return false;
    return true;
}

export function InstanceDataDTOFromJSON(json: any): InstanceDataDTO {
    return InstanceDataDTOFromJSONTyped(json, false);
}

export function InstanceDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerId': json['ownerId'],
        'agentFramework': json['agentFramework'],
        'providerId': json['providerId'],
        'externalId': json['externalId'],
        'osType': json['osType'],
        'hostingType': json['hostingType'],
        'cloudProvider': json['cloudProvider'],
        'name': json['name'],
        'modelPrimary': json['modelPrimary'],
        'models': json['models'],
        'status': json['status'],
        'desiredStatus': json['desiredStatus'],
        'endpoint': json['endpoint'],
        'bridgeId': json['bridgeId'],
        'identityId': json['identityId'],
        'totalRunSeconds': json['totalRunSeconds'],
        'connectivity': json['connectivity'],
        'haltReason': json['haltReason'] == null ? undefined : json['haltReason'],
        'providerConfig': json['providerConfig'],
        'publicIp': json['publicIp'] == null ? undefined : json['publicIp'],
        'clusterId': json['clusterId'] == null ? undefined : json['clusterId'],
        'region': json['region'] == null ? undefined : json['region'],
        'imageId': json['imageId'] == null ? undefined : json['imageId'],
        'imageRef': json['imageRef'] == null ? undefined : json['imageRef'],
        'isTrial': json['isTrial'] == null ? undefined : json['isTrial'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'systemPrompt': json['systemPrompt'] == null ? undefined : json['systemPrompt'],
        'mcpServers': json['mcpServers'] == null ? undefined : json['mcpServers'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'stoppedAt': json['stoppedAt'] == null ? undefined : (new Date(json['stoppedAt'])),
        'statusEnteredAt': json['statusEnteredAt'] == null ? undefined : (new Date(json['statusEnteredAt'])),
        'connectivityUpdatedAt': json['connectivityUpdatedAt'] == null ? undefined : (new Date(json['connectivityUpdatedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'screenshotUrl': json['screenshotUrl'] == null ? undefined : json['screenshotUrl'],
        'screenshotUpdatedAt': json['screenshotUpdatedAt'] == null ? undefined : (new Date(json['screenshotUpdatedAt'])),
    };
}

export function InstanceDataDTOToJSON(json: any): InstanceDataDTO {
    return InstanceDataDTOToJSONTyped(json, false);
}

export function InstanceDataDTOToJSONTyped(value?: InstanceDataDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerId': value['ownerId'],
        'agentFramework': value['agentFramework'],
        'providerId': value['providerId'],
        'externalId': value['externalId'],
        'osType': value['osType'],
        'hostingType': value['hostingType'],
        'cloudProvider': value['cloudProvider'],
        'name': value['name'],
        'modelPrimary': value['modelPrimary'],
        'models': value['models'],
        'status': value['status'],
        'desiredStatus': value['desiredStatus'],
        'endpoint': value['endpoint'],
        'bridgeId': value['bridgeId'],
        'identityId': value['identityId'],
        'totalRunSeconds': value['totalRunSeconds'],
        'connectivity': value['connectivity'],
        'haltReason': value['haltReason'],
        'providerConfig': value['providerConfig'],
        'publicIp': value['publicIp'],
        'clusterId': value['clusterId'],
        'region': value['region'],
        'imageId': value['imageId'],
        'imageRef': value['imageRef'],
        'isTrial': value['isTrial'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'errorMessage': value['errorMessage'],
        'systemPrompt': value['systemPrompt'],
        'mcpServers': value['mcpServers'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'stoppedAt': value['stoppedAt'] == null ? undefined : ((value['stoppedAt']).toISOString()),
        'statusEnteredAt': value['statusEnteredAt'] == null ? undefined : ((value['statusEnteredAt']).toISOString()),
        'connectivityUpdatedAt': value['connectivityUpdatedAt'] == null ? undefined : ((value['connectivityUpdatedAt']).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'screenshotUrl': value['screenshotUrl'],
        'screenshotUpdatedAt': value['screenshotUpdatedAt'] == null ? undefined : ((value['screenshotUpdatedAt']).toISOString()),
    };
}

