/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstanceDataDTO } from './InstanceDataDTO';
import {
    InstanceDataDTOFromJSON,
    InstanceDataDTOFromJSONTyped,
    InstanceDataDTOToJSON,
    InstanceDataDTOToJSONTyped,
} from './InstanceDataDTO';

/**
 * 
 * @export
 * @interface InstanceResponse
 */
export interface InstanceResponse {
    /**
     * 
     * @type {boolean}
     * @memberof InstanceResponse
     */
    success: InstanceResponseSuccessEnum;
    /**
     * 
     * @type {InstanceDataDTO}
     * @memberof InstanceResponse
     */
    data: InstanceDataDTO;
}


/**
 * @export
 */
export const InstanceResponseSuccessEnum = {
    True: true
} as const;
export type InstanceResponseSuccessEnum = typeof InstanceResponseSuccessEnum[keyof typeof InstanceResponseSuccessEnum];


/**
 * Check if a given object implements the InstanceResponse interface.
 */
export function instanceOfInstanceResponse(value: object): value is InstanceResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InstanceResponseFromJSON(json: any): InstanceResponse {
    return InstanceResponseFromJSONTyped(json, false);
}

export function InstanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': InstanceDataDTOFromJSON(json['data']),
    };
}

export function InstanceResponseToJSON(json: any): InstanceResponse {
    return InstanceResponseToJSONTyped(json, false);
}

export function InstanceResponseToJSONTyped(value?: InstanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': InstanceDataDTOToJSON(value['data']),
    };
}

