/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvokeAgentResponseAllOfData
 */
export interface InvokeAgentResponseAllOfData {
    /**
     * Agent reply text.
     * @type {string}
     * @memberof InvokeAgentResponseAllOfData
     */
    text: string;
    /**
     * Conversation context ID (channel ID).
     * @type {string}
     * @memberof InvokeAgentResponseAllOfData
     */
    contextId: string;
    /**
     * Whether the agent's reply indicated an error.
     * @type {boolean}
     * @memberof InvokeAgentResponseAllOfData
     */
    isError: boolean;
}

/**
 * Check if a given object implements the InvokeAgentResponseAllOfData interface.
 */
export function instanceOfInvokeAgentResponseAllOfData(value: object): value is InvokeAgentResponseAllOfData {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('contextId' in value) || value['contextId'] === undefined) return false;
    if (!('isError' in value) || value['isError'] === undefined) return false;
    return true;
}

export function InvokeAgentResponseAllOfDataFromJSON(json: any): InvokeAgentResponseAllOfData {
    return InvokeAgentResponseAllOfDataFromJSONTyped(json, false);
}

export function InvokeAgentResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeAgentResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'contextId': json['context_id'],
        'isError': json['is_error'],
    };
}

export function InvokeAgentResponseAllOfDataToJSON(json: any): InvokeAgentResponseAllOfData {
    return InvokeAgentResponseAllOfDataToJSONTyped(json, false);
}

export function InvokeAgentResponseAllOfDataToJSONTyped(value?: InvokeAgentResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'context_id': value['contextId'],
        'is_error': value['isError'],
    };
}

