/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level protocol endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvokeAgentResponseAllOfData } from './InvokeAgentResponseAllOfData';
import {
    InvokeAgentResponseAllOfDataFromJSON,
    InvokeAgentResponseAllOfDataFromJSONTyped,
    InvokeAgentResponseAllOfDataToJSON,
    InvokeAgentResponseAllOfDataToJSONTyped,
} from './InvokeAgentResponseAllOfData';

/**
 * 
 * @export
 * @interface InvokeAgentResponse
 */
export interface InvokeAgentResponse {
    /**
     * 
     * @type {boolean}
     * @memberof InvokeAgentResponse
     */
    success: InvokeAgentResponseSuccessEnum;
    /**
     * 
     * @type {InvokeAgentResponseAllOfData}
     * @memberof InvokeAgentResponse
     */
    data: InvokeAgentResponseAllOfData;
}


/**
 * @export
 */
export const InvokeAgentResponseSuccessEnum = {
    True: true
} as const;
export type InvokeAgentResponseSuccessEnum = typeof InvokeAgentResponseSuccessEnum[keyof typeof InvokeAgentResponseSuccessEnum];


/**
 * Check if a given object implements the InvokeAgentResponse interface.
 */
export function instanceOfInvokeAgentResponse(value: object): value is InvokeAgentResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvokeAgentResponseFromJSON(json: any): InvokeAgentResponse {
    return InvokeAgentResponseFromJSONTyped(json, false);
}

export function InvokeAgentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvokeAgentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': InvokeAgentResponseAllOfDataFromJSON(json['data']),
    };
}

export function InvokeAgentResponseToJSON(json: any): InvokeAgentResponse {
    return InvokeAgentResponseToJSONTyped(json, false);
}

export function InvokeAgentResponseToJSONTyped(value?: InvokeAgentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': InvokeAgentResponseAllOfDataToJSON(value['data']),
    };
}

