/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProviderCatalogItem } from './ProviderCatalogItem';
import {
    ProviderCatalogItemFromJSON,
    ProviderCatalogItemFromJSONTyped,
    ProviderCatalogItemToJSON,
    ProviderCatalogItemToJSONTyped,
} from './ProviderCatalogItem';

/**
 * 
 * @export
 * @interface ProvidersListResponse
 */
export interface ProvidersListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ProvidersListResponse
     */
    success: ProvidersListResponseSuccessEnum;
    /**
     * 
     * @type {Array<ProviderCatalogItem>}
     * @memberof ProvidersListResponse
     */
    data: Array<ProviderCatalogItem>;
}


/**
 * @export
 */
export const ProvidersListResponseSuccessEnum = {
    True: true
} as const;
export type ProvidersListResponseSuccessEnum = typeof ProvidersListResponseSuccessEnum[keyof typeof ProvidersListResponseSuccessEnum];


/**
 * Check if a given object implements the ProvidersListResponse interface.
 */
export function instanceOfProvidersListResponse(value: object): value is ProvidersListResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProvidersListResponseFromJSON(json: any): ProvidersListResponse {
    return ProvidersListResponseFromJSONTyped(json, false);
}

export function ProvidersListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvidersListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(ProviderCatalogItemFromJSON)),
    };
}

export function ProvidersListResponseToJSON(json: any): ProvidersListResponse {
    return ProvidersListResponseToJSONTyped(json, false);
}

export function ProvidersListResponseToJSONTyped(value?: ProvidersListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(ProviderCatalogItemToJSON)),
    };
}

