/* tslint:disable */
/* eslint-disable */
/**
 * BeeOS OpenAPI (user contract)
 * The **BeeOS OpenAPI** user contract. The sole implementer is **[`services/openapi-gateway`](../services/openapi-gateway)** (`openapi-gw`, local `:8095`). SDKs (Go / TypeScript) published under [`sdks/beeos-ai-sdk-go`](../../sdks/beeos-ai-sdk-go) and [`sdks/beeos-ai-sdk`](../../sdks/beeos-ai-sdk) are generated directly from this document.  The main user Gateway (`services/gateway`, `:9080`) serves web / mobile / desktop clients and is **not** described by this document. It maintains its own route set independent of the SDK contract.  **Auth:** every operation requires either a user **JWT** or a **`oag_`** User API Key, both on `Authorization: Bearer`. Agent-level endpoints (A2A JSON-RPC with `bak_`, MCP) live in [beeos-agent-integration-v1.yaml](beeos-agent-integration-v1.yaml) and are hosted by A2A Gateway / MCP Gateway — not by `openapi-gateway`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringResponse
 */
export interface StringResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StringResponse
     */
    success: StringResponseSuccessEnum;
    /**
     * 
     * @type {string}
     * @memberof StringResponse
     */
    data: string;
}


/**
 * @export
 */
export const StringResponseSuccessEnum = {
    True: true
} as const;
export type StringResponseSuccessEnum = typeof StringResponseSuccessEnum[keyof typeof StringResponseSuccessEnum];


/**
 * Check if a given object implements the StringResponse interface.
 */
export function instanceOfStringResponse(value: object): value is StringResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StringResponseFromJSON(json: any): StringResponse {
    return StringResponseFromJSONTyped(json, false);
}

export function StringResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'],
    };
}

export function StringResponseToJSON(json: any): StringResponse {
    return StringResponseToJSONTyped(json, false);
}

export function StringResponseToJSONTyped(value?: StringResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
    };
}

